"""bp_ir - unified semantic IR for Blueprint graphs.

One model bridging all three operations:
    parse(text)      verbose copy/paste text  ->  Graph  (full fidelity)
    Graph.render()   Graph  ->  import text    (re-injectable)
    Graph.compact()  Graph  ->  navigable view (delegates to bp_compact)
    edit ops         find / add / wire / remove on a Graph

Fidelity: a PARSED node keeps every pin attribute verbatim (PinType.*, defaults,
flags) so it re-renders identically; only PinId / PinName / Direction / LinkedTo
are promoted to fields so wiring is editable. NEW (authored) nodes carry only
intent -- UE reconstructs the rest on import.

Editing existing graphs uses 'replace': ImportNodesFromText cross-links only
within the pasted set, so to rewire pre-existing nodes you parse the whole graph,
mutate the IR (new wires are now intra-set), clear the graph
(bp_bridge.clear_graph), and re-import Graph.render() as one set. See
examples/edit_graph.py.

Pure stdlib -- parse/render/compact run offline; only the apply step needs the editor.

TYPED PINS (important): a default or data wire only MERGES into a node's canonical pin
on import if the authored pin carries a matching PinType; a typeless pin ORPHANS
(bOrphanedPin=True) and the node silently uses the engine's autogenerated default. So
for any non-string default and for VariableGet/Set pins, type the pin:
    g.typed_input(call, "LocationRule", "SnapToTarget", "byte", enum_path("/Script/Engine.EAttachmentRule"))
    g.typed_input(call, "SocketName", "attachrider", "name")
    rider = g.var_get("Rider", "object", obj_path("/Script/ConanSandbox.ConanCharacter"))
    mesh  = g.var_get("Mesh", "object", obj_path("/Script/Engine.SkeletalMeshComponent"),
                      parent="/Script/Engine.Character")   # reads Mesh off a target
Verify after inject: zero bOrphanedPin=True pins == every default/wire merged.
"""
import re
import uuid

_BPG = "/Script/BlueprintGraph."
_CLASS_OBJ = "/Script/CoreUObject.Class'%s'"


def guid():
    return uuid.uuid4().hex.upper()


# --- PinType sub-object path helpers -----------------------------------------
# A scalar/enum/name/bool/object/struct default OR a data wire only MERGES into the
# canonical pin on ImportNodesFromText if the authored pin carries a matching PinType;
# a typeless pin orphans (bOrphanedPin=True) and the node silently keeps the engine's
# autogenerated default. Use Pin.typed(...) with these to build the PinSubCategoryObject.
def obj_path(cls_path):
    """object pin sub-type, e.g. obj_path('/Script/Engine.SkeletalMeshComponent')."""
    return "/Script/CoreUObject.Class'%s'" % cls_path


def enum_path(e_path):
    """byte/enum pin sub-type, e.g. enum_path('/Script/Engine.EAttachmentRule')."""
    return "/Script/CoreUObject.Enum'%s'" % e_path


def struct_path(s_path):
    """struct pin sub-type, e.g. struct_path('/Script/CoreUObject.Transform')."""
    return "/Script/CoreUObject.ScriptStruct'%s'" % s_path


# ----------------------------------------------------------------------------
# low-level token splitting (UE prop lists nest parens and quote strings)
# ----------------------------------------------------------------------------
def _split_top(s):
    parts, depth, inq, cur = [], 0, False, []
    for ch in s:
        if ch == '"':
            inq = not inq
        elif not inq and ch == "(":
            depth += 1
        elif not inq and ch == ")":
            depth -= 1
        elif not inq and ch == "," and depth == 0:
            parts.append("".join(cur)); cur = []; continue
        cur.append(ch)
    if cur:
        parts.append("".join(cur))
    return parts


def _kv(tok):
    i = tok.find("=")
    return (tok[:i].strip(), tok[i + 1:].strip()) if i >= 0 else (tok.strip(), None)


def _unq(v):
    return v[1:-1] if v and len(v) >= 2 and v[0] == '"' and v[-1] == '"' else v


# ----------------------------------------------------------------------------
# Pin
# ----------------------------------------------------------------------------
class Pin(object):
    def __init__(self, name, pid=None, direction=None):
        self.name = name
        self.id = pid or guid()
        self.dir = direction               # 'EGPD_Input' / 'EGPD_Output' / None
        self.links = []                    # [(node_name, target_pin_id)]
        self.extra = []                    # ordered [(key, raw_value)] verbatim

    def set(self, key, raw_value):
        for i, (k, _) in enumerate(self.extra):
            if k == key:
                self.extra[i] = (key, raw_value); return
        self.extra.append((key, raw_value))

    def get(self, key):
        for k, v in self.extra:
            if k == key:
                return v
        return None

    # --- fluent typing (so defaults/wires merge instead of orphaning) ---------
    def typed(self, category, sub_object=None, direction=None):
        """Give this pin an explicit PinType. category: 'byte'/'name'/'bool'/
        'object'/'struct'/... ; sub_object: an obj_path()/enum_path()/struct_path()
        string for object/enum/struct pins. Returns self (chainable)."""
        if direction:
            self.dir = direction
        self.set("PinType.PinCategory", '"%s"' % category)
        if sub_object:
            self.set("PinType.PinSubCategoryObject", sub_object)
        return self

    def literal(self, value):
        """Set a scalar/enum/name/bool DefaultValue (string form). Chainable.
        Pair with .typed(...) for non-string pins or it orphans."""
        self.set("DefaultValue", '"%s"' % value)
        return self

    def object_literal(self, asset_path):
        """Set an object-asset literal default (DefaultObject). Chainable.
        Pair with .typed('object', obj_path(cls))."""
        self.set("DefaultObject", asset_path)
        return self

    @property
    def cat(self):
        return _unq(self.get("PinType.PinCategory") or "") or None

    @property
    def default(self):
        d = self.get("DefaultValue")
        return _unq(d) if d is not None else None

    @classmethod
    def parse(cls, body):
        p = cls("?")
        for k, v in (_kv(t) for t in _split_top(body)):
            if k == "PinId":
                p.id = v
            elif k == "PinName":
                p.name = _unq(v)
            elif k == "Direction":
                p.dir = _unq(v)
            elif k == "LinkedTo":
                inner = v.strip()
                if inner.startswith("("):
                    inner = inner[1:-1] if inner.endswith(")") else inner[1:]
                for ref in _split_top(inner):
                    ref = ref.strip()
                    if ref:
                        nm, _, pid = ref.partition(" ")
                        p.links.append((nm.strip(), pid.strip()))
            else:
                p.extra.append((k, v))
        return p

    def render(self):
        parts = ["PinId=%s" % self.id, 'PinName="%s"' % self.name]
        if self.dir:
            parts.append('Direction="%s"' % self.dir)
        for k, v in self.extra:
            parts.append("%s=%s" % (k, v) if v is not None else k)
        if self.links:
            parts.append("LinkedTo=(%s,)" % ",".join("%s %s" % (n, p) for n, p in self.links))
        return "CustomProperties Pin (%s)" % ",".join(parts)


# ----------------------------------------------------------------------------
# Node
# ----------------------------------------------------------------------------
class Node(object):
    def __init__(self, name, cls):
        self.name = name
        self.cls = cls                     # full /Script/... class path
        self.guid = guid()
        self.header = []                   # ordered [(key, raw_value_or_None)]
        self.pins = []

    def pin(self, name):
        for p in self.pins:
            if p.name == name:
                return p
        p = Pin(name)
        self.pins.append(p)
        return p

    def set(self, key, raw_value=None):
        for i, (k, _) in enumerate(self.header):
            if k == key:
                self.header[i] = (key, raw_value); return
        self.header.append((key, raw_value))

    def render(self):
        out = ['Begin Object Class=%s Name="%s"' % (self.cls, self.name)]
        for k, v in self.header:
            out.append("   %s=%s" % (k, v) if v is not None else "   " + k)
        out.append("   NodeGuid=%s" % self.guid)
        for p in self.pins:
            out.append("   " + p.render())
        out.append("End Object")
        return "\n".join(out)


# ----------------------------------------------------------------------------
# Graph
# ----------------------------------------------------------------------------
class Graph(object):
    def __init__(self, name="EventGraph"):
        self.name = name
        self.nodes = []
        self._counts = {}

    # -- lookup / mutate --
    def find(self, name):
        for n in self.nodes:
            if n.name == name:
                return n
        return None

    def by_type(self, short):
        return [n for n in self.nodes if short in n.cls]

    def remove(self, node):
        # drop every link into/out of this node first, else other nodes keep
        # mirror LinkedTo refs to a node that no longer exists (which a later
        # node reusing the same auto-generated name would silently capture).
        for p in list(node.pins):
            self.unwire(node, p.name)
        self.nodes.remove(node)

    def add(self, node):
        self.nodes.append(node)
        return node

    def _name(self, base):
        self._counts[base] = self._counts.get(base, 0) + 1
        return "K2Node_%s_%d" % (base, self._counts[base])

    # -- authoring factories (new nodes carry only intent) --
    def node(self, short_cls, header, base="Node", pos=(0, 0)):
        cls = short_cls if short_cls.startswith("/Script/") else _BPG + short_cls
        n = Node(self._name(base), cls)
        for h in header:
            k, v = _kv(h) if "=" in h else (h, None)
            n.header.append((k, v))
        n.set("NodePosX", str(pos[0]))
        n.set("NodePosY", str(pos[1]))
        return self.add(n)

    def event(self, member, parent="/Script/Engine.Actor", pos=(0, 0)):
        return self.node("K2Node_Event",
                         ['EventReference=(MemberParent="%s",MemberName="%s")'
                          % (_CLASS_OBJ % parent, member), "bOverrideFunction=True"],
                         base="Event", pos=pos)

    def custom_event(self, name, pos=(0, 0)):
        return self.node("K2Node_CustomEvent", ['CustomFunctionName="%s"' % name],
                         base="CustomEvent", pos=pos)

    def call(self, member, parent, inputs=None, pos=(0, 0)):
        n = self.node("K2Node_CallFunction",
                      ['FunctionReference=(MemberParent="%s",MemberName="%s")'
                       % (_CLASS_OBJ % parent, member)], base="CallFunction", pos=pos)
        for pn, val in (inputs or {}).items():
            p = n.pin(pn)
            p.dir = "EGPD_Input"
            p.set("DefaultValue", '"%s"' % val)
        return n

    def branch(self, pos=(0, 0)):
        return self.node("K2Node_IfThenElse", [], base="IfThenElse", pos=pos)

    # ForEachLoop standard-macro instance (ref extracted from the engine StandardMacros)
    _FOREACH_REF = ('MacroGraphReference=(MacroGraph="/Script/Engine.EdGraph\''
                    '/Engine/EditorBlueprintResources/StandardMacros.StandardMacros:ForEachLoop\'",'
                    'GraphBlueprint="/Script/Engine.Blueprint\''
                    '/Engine/EditorBlueprintResources/StandardMacros.StandardMacros\'",'
                    'GraphGuid=99DBFD5540A796041F72A5A9DA655026)')

    def foreach(self, elem_cls_path, pos=(0, 0)):
        """ForEachLoop over an array. Pins: 'Exec'(in), 'Array'(in, array of elem),
        'LoopBody'(out exec), 'Array Element'(out, elem), 'Array Index'(out int),
        'Completed'(out exec). The Array + Array Element pins are typed to
        elem_cls_path (an object class path) so the macro's wildcard resolves on paste."""
        n = self.node("K2Node_MacroInstance", [self._FOREACH_REF], base="ForEach", pos=pos)
        arr = n.pin("Array"); arr.dir = "EGPD_Input"
        arr.set("PinType.PinCategory", '"object"')
        arr.set("PinType.PinSubCategoryObject", obj_path(elem_cls_path))
        arr.set("PinType.ContainerType", "Array")
        el = n.pin("Array Element"); el.dir = "EGPD_Output"
        el.set("PinType.PinCategory", '"object"')
        el.set("PinType.PinSubCategoryObject", obj_path(elem_cls_path))
        return n

    # -- typed authoring (avoids the orphan trap; see Pin.typed) --------------
    def typed_input(self, node, name, value, category, sub=None):
        """Set a TYPED default on an input pin of `node` so it merges into the
        canonical pin instead of orphaning. e.g.
        typed_input(n, 'LocationRule', 'SnapToTarget', 'byte', enum_path('/Script/Engine.EAttachmentRule'))
        typed_input(n, 'SocketName', 'attachrider', 'name')."""
        return node.pin(name).typed(category, sub, direction="EGPD_Input").literal(value)

    def var_get(self, name, category="object", sub=None, parent=None, pos=(0, 0)):
        """Typed VariableGet. self-context if parent is None; else reads `name`
        off a target object (wire the target into the returned node's 'self' pin),
        with the target pin typed to `parent` (an obj_path string). The output pin
        (named `name`) is typed (category/sub) so its links survive reconstruction."""
        if parent is None:
            hdr = ['VariableReference=(MemberName="%s",bSelfContext=True)' % name]
        else:
            hdr = ['VariableReference=(MemberName="%s",MemberParent="%s",bSelfContext=False)'
                   % (name, parent if parent.startswith("/Script/CoreUObject") else obj_path(parent))]
        n = self.node("K2Node_VariableGet", hdr, base="VariableGet", pos=pos)
        n.pin(name).typed(category, sub, direction="EGPD_Output")
        if parent is not None:
            n.pin("self").typed("object", parent if parent.startswith("/Script/CoreUObject")
                                else obj_path(parent), direction="EGPD_Input")
        return n

    def var_set(self, name, category="object", sub=None, pos=(0, 0)):
        """Typed self-context VariableSet. Value input pin is named `name`."""
        n = self.node("K2Node_VariableSet",
                      ['VariableReference=(MemberName="%s",bSelfContext=True)' % name],
                      base="VariableSet", pos=pos)
        n.pin(name).typed(category, sub, direction="EGPD_Input")
        return n

    # -- wiring --
    def wire(self, src, src_pin, dst, dst_pin, exec=True):
        sp = src.pin(src_pin); sp.dir = "EGPD_Output"
        dp = dst.pin(dst_pin); dp.dir = "EGPD_Input"
        if exec:
            sp.set("PinType.PinCategory", '"exec"')
            dp.set("PinType.PinCategory", '"exec"')
        sp.links.append((dst.name, dp.id))
        dp.links.append((src.name, sp.id))

    def unwire(self, node, pin_name):
        """Drop all links on a pin (and the mirror refs on the other ends)."""
        p = node.pin(pin_name)
        for tgt_name, tgt_pid in list(p.links):
            tn = self.find(tgt_name)
            if tn:
                for tp in tn.pins:
                    tp.links = [(n, i) for (n, i) in tp.links if i != p.id]
        p.links = []

    # -- I/O --
    def render(self):
        return "\n".join(n.render() for n in self.nodes) + "\n"

    def compact(self):
        # compact our own nodes; render() drops the derived ExportPath, so retag
        # the re-parsed nodes with this graph's name instead of relying on it.
        import bp_compact as bc
        nodes = bc.parse_nodes(self.render())
        for nd in nodes:
            nd.graph = self.name
        return bc.compact_graph(nodes, self.name)

    @classmethod
    def parse(cls, text):
        """Parse all node blocks, grouped by graph (from each node's ExportPath).
        Returns {graph_name: Graph}."""
        graphs = {}
        cur = None
        depth = 0
        for raw in text.splitlines():
            line = raw.strip()
            if line.startswith("Begin Object"):
                depth += 1
                if depth == 1:
                    c = re.search(r"Class=(\S+)", line)
                    nm = re.search(r'Name="([^"]+)"', line)
                    gp = re.search(r":([^.\']+)\.", line)
                    gname = gp.group(1) if gp else "EventGraph"
                    cur = Node(nm.group(1) if nm else "?", c.group(1) if c else "?")
                    graphs.setdefault(gname, cls(gname)).nodes.append(cur)
                continue
            if line.startswith("End Object"):
                depth -= 1
                if depth == 0:
                    cur = None
                continue
            if cur is None or depth != 1:
                continue
            if line.startswith("CustomProperties Pin"):
                lp, rp = line.find("("), line.rfind(")")
                if lp >= 0 and rp > lp:
                    cur.pins.append(Pin.parse(line[lp + 1:rp]))
            else:
                k, v = _kv(line)
                if k == "NodeGuid":
                    cur.guid = v
                else:
                    cur.header.append((k, v))
        return graphs

    @classmethod
    def parse_one(cls, text, name=None):
        gs = cls.parse(text)
        if name and name in gs:
            return gs[name]
        return next(iter(gs.values())) if gs else cls(name or "EventGraph")
